### ISSUE TITLE
Paint and Words Failed to Start (Submitted on Paint and Words)

### ISSUE THREAD

**Issue by Wyvert** [sugarlabs/words-activity#11] opened 2018-01-23 21:50 UTC
In SOAS, Paint failed to start. Words failed to start. When opening up the application, it loads a blank screen as if the application is loading, but a grey box appears that says application failed to start.

Furthermore, when the Paint icon was clicked in the main menu, it changed the color of the icon to indicate that the program had been used. When Words was clicked in the main menu, the icon did not change color.

**Comment by quozl** [comment] 2018-01-24 03:41
Works for me.  Not enough information.  What version of SoaS?  What version of Words?  What was found in the Log activity for Words?  Have you tried the master branch of this repository; a recent change https://github.com/sugarlabs/words-activity/commit/ae8ccca439f34f99df6fb7a34313ab57af9e5e9e may cause fail to start if the Fedora package has the wrong dependencies.

**Comment by quozl** [comment] 2018-01-25 00:12
Reproduced on Words-22 on `Fedora-SoaS-Live-x86_64-27-1.6.iso`.

Cause is that Fedora 27 no longer includes WebKit API 3.0 and the Fedora package `sugar-words` does not correctly identify the dependencies.  Fedora's problems aren't our concern upstream though.

Will be fixed in the next release of Words, which will include port to WebKit API 4.0, see
https://github.com/sugarlabs/words-activity/commit/ae8ccca439f34f99df6fb7a34313ab57af9e5e9e.

**Closed as completed by quozl** 2018-01-25 00:12 UTC
